//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkrainianCurrency.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UkrainianCurrency.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppbarAbout {
            get {
                return ResourceManager.GetString("AppbarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppbarSettings {
            get {
                return ResourceManager.GetString("AppbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string AppbarUpdate {
            get {
                return ResourceManager.GetString("AppbarUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA Currency.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Khmelenko Lab.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Bank.
        /// </summary>
        public static string Bank_Active {
            get {
                return ResourceManager.GetString("Bank_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Akcent.
        /// </summary>
        public static string Bank_Akcent {
            get {
                return ResourceManager.GetString("Bank_Akcent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All banks.
        /// </summary>
        public static string Bank_All {
            get {
                return ResourceManager.GetString("Bank_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha bank.
        /// </summary>
        public static string Bank_Alpha {
            get {
                return ResourceManager.GetString("Bank_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Agricole.
        /// </summary>
        public static string Bank_CreditAgricole {
            get {
                return ResourceManager.GetString("Bank_CreditAgricole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditprombank.
        /// </summary>
        public static string Bank_Creditprom {
            get {
                return ResourceManager.GetString("Bank_Creditprom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltabank.
        /// </summary>
        public static string Bank_Delta {
            get {
                return ResourceManager.GetString("Bank_Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finansy i Kredyt.
        /// </summary>
        public static string Bank_Fin {
            get {
                return ResourceManager.GetString("Bank_Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Finansova iniciatyva.
        /// </summary>
        public static string Bank_Fin_initiative {
            get {
                return ResourceManager.GetString("Bank_Fin_initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Forum.
        /// </summary>
        public static string Bank_Forum {
            get {
                return ResourceManager.GetString("Bank_Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEX bank.
        /// </summary>
        public static string Bank_Imex {
            get {
                return ResourceManager.GetString("Bank_Imex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Khreshchatyk.
        /// </summary>
        public static string Bank_Khreshchatyk {
            get {
                return ResourceManager.GetString("Bank_Khreshchatyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Mercury.
        /// </summary>
        public static string Bank_Mercury {
            get {
                return ResourceManager.GetString("Bank_Mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP bank.
        /// </summary>
        public static string Bank_Otp {
            get {
                return ResourceManager.GetString("Bank_Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pireus bank.
        /// </summary>
        public static string Bank_Pireus {
            get {
                return ResourceManager.GetString("Bank_Pireus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivdencombank.
        /// </summary>
        public static string Bank_Pivdencom {
            get {
                return ResourceManager.GetString("Bank_Pivdencom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Pivdennyi.
        /// </summary>
        public static string Bank_Pivdennyi {
            get {
                return ResourceManager.GetString("Bank_Pivdennyi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prominvestbank.
        /// </summary>
        public static string Bank_Prominvest {
            get {
                return ResourceManager.GetString("Bank_Prominvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank PUMP.
        /// </summary>
        public static string Bank_Pumb {
            get {
                return ResourceManager.GetString("Bank_Pumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiffaisen bank.
        /// </summary>
        public static string Bank_Raiffaisen {
            get {
                return ResourceManager.GetString("Bank_Raiffaisen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodovid bank.
        /// </summary>
        public static string Bank_Rodovid {
            get {
                return ResourceManager.GetString("Bank_Rodovid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Tavrika.
        /// </summary>
        public static string Bank_Tavrika {
            get {
                return ResourceManager.GetString("Bank_Tavrika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicredit bank.
        /// </summary>
        public static string Bank_Unicredit {
            get {
                return ResourceManager.GetString("Bank_Unicredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAB bank.
        /// </summary>
        public static string Bank_Vab {
            get {
                return ResourceManager.GetString("Bank_Vab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string BuyLabel {
            get {
                return ResourceManager.GetString("BuyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Ukraine.
        /// </summary>
        public static string City_All {
            get {
                return ResourceManager.GetString("City_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzhgorod.
        /// </summary>
        public static string City_Carpathian {
            get {
                return ResourceManager.GetString("City_Carpathian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherkasy.
        /// </summary>
        public static string City_Cherkasy {
            get {
                return ResourceManager.GetString("City_Cherkasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chernihiv.
        /// </summary>
        public static string City_Chernihiv {
            get {
                return ResourceManager.GetString("City_Chernihiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chernivtsi.
        /// </summary>
        public static string City_Chernivtsi {
            get {
                return ResourceManager.GetString("City_Chernivtsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simferopol.
        /// </summary>
        public static string City_Crimea {
            get {
                return ResourceManager.GetString("City_Crimea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnipropetrovsk.
        /// </summary>
        public static string City_Dnepr {
            get {
                return ResourceManager.GetString("City_Dnepr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donetsk.
        /// </summary>
        public static string City_Donetsk {
            get {
                return ResourceManager.GetString("City_Donetsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivano-Frankivsk.
        /// </summary>
        public static string City_IF {
            get {
                return ResourceManager.GetString("City_IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kharkiv.
        /// </summary>
        public static string City_Kharkiv {
            get {
                return ResourceManager.GetString("City_Kharkiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kherson.
        /// </summary>
        public static string City_Kherson {
            get {
                return ResourceManager.GetString("City_Kherson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmelnytskyi.
        /// </summary>
        public static string City_Khmel {
            get {
                return ResourceManager.GetString("City_Khmel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirovohrad.
        /// </summary>
        public static string City_Kirovohrad {
            get {
                return ResourceManager.GetString("City_Kirovohrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyiv.
        /// </summary>
        public static string City_Kyiv {
            get {
                return ResourceManager.GetString("City_Kyiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luhansk.
        /// </summary>
        public static string City_Luhansk {
            get {
                return ResourceManager.GetString("City_Luhansk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lviv.
        /// </summary>
        public static string City_Lviv {
            get {
                return ResourceManager.GetString("City_Lviv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mykolaiv.
        /// </summary>
        public static string City_Mykolaiv {
            get {
                return ResourceManager.GetString("City_Mykolaiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesa.
        /// </summary>
        public static string City_Odessa {
            get {
                return ResourceManager.GetString("City_Odessa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poltava.
        /// </summary>
        public static string City_Poltava {
            get {
                return ResourceManager.GetString("City_Poltava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivne.
        /// </summary>
        public static string City_Rivne {
            get {
                return ResourceManager.GetString("City_Rivne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumy.
        /// </summary>
        public static string City_Sumy {
            get {
                return ResourceManager.GetString("City_Sumy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ternopil.
        /// </summary>
        public static string City_Tern {
            get {
                return ResourceManager.GetString("City_Tern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinnitsia.
        /// </summary>
        public static string City_Vinnitsia {
            get {
                return ResourceManager.GetString("City_Vinnitsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lutsk.
        /// </summary>
        public static string City_Volyn {
            get {
                return ResourceManager.GetString("City_Volyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhytomyr.
        /// </summary>
        public static string City_Zhytomyr {
            get {
                return ResourceManager.GetString("City_Zhytomyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaporizhzhya.
        /// </summary>
        public static string City_Zp {
            get {
                return ResourceManager.GetString("City_Zp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.khmelenko@gmail.com.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency: UAH.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error occurred. Please, try later..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is available for current country/city.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connection.
        /// </summary>
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select bank.
        /// </summary>
        public static string SelectBank {
            get {
                return ResourceManager.GetString("SelectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select city.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string SellLabel {
            get {
                return ResourceManager.GetString("SellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank.
        /// </summary>
        public static string SettingsScr_BankLabel {
            get {
                return ResourceManager.GetString("SettingsScr_BankLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string SettingsScr_CityLabel {
            get {
                return ResourceManager.GetString("SettingsScr_CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsScr_Title {
            get {
                return ResourceManager.GetString("SettingsScr_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated: .
        /// </summary>
        public static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 1.01.003.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
